from __future__ import annotations

import asyncio
import json
import shlex
import subprocess
import time
from pathlib import Path
from typing import Any

from ..base import ExecutionPlan, ExecutionResult


class AppiumRunner:
    """Mobile runner adapter using an explicit external Appium test command.

    The framework does not impose an Appium client dependency. Applications can
    supply a command generated by their native test project; stdout may contain
    a JSON summary with passed/failed/skipped fields.
    """

    name = "appium"

    async def execute(self, plan: ExecutionPlan) -> ExecutionResult:
        command = plan.fixtures.get("command")
        if not command:
            return ExecutionResult(
                run_id=plan.id,
                runner=self.name,
                status="blocked",
                summary={"passed": 0, "failed": 0, "skipped": len(plan.scenarios)},
                failures=[
                    {
                        "id": "appium-preflight",
                        "category": "runner_error",
                        "message": "Appium runner requires fixtures.command",
                        "retryable": False,
                    }
                ],
                metrics={"preflight": "missing-command"},
            )
        argv = shlex.split(command) if isinstance(command, str) else [str(item) for item in command]
        return await asyncio.to_thread(self._run, argv, plan)

    def collect_artifacts(self, result: ExecutionResult) -> list[dict[str, Any]]:
        return list(result.artifacts)

    def _run(self, argv: list[str], plan: ExecutionPlan) -> ExecutionResult:
        started = time.monotonic()
        timeout = int(plan.env.get("timeout_seconds") or 900)
        cwd = Path(str(plan.fixtures.get("cwd") or Path.cwd()))
        try:
            completed = subprocess.run(
                argv,
                cwd=str(cwd),
                capture_output=True,
                text=True,
                encoding="utf-8",
                errors="replace",
                timeout=timeout,
                check=False,
            )
        except subprocess.TimeoutExpired as exc:
            return ExecutionResult(
                run_id=plan.id,
                runner=self.name,
                status="failed",
                summary={"passed": 0, "failed": 1, "skipped": 0, "duration_ms": timeout * 1000},
                failures=[
                    {
                        "id": "appium-timeout",
                        "category": "runner_error",
                        "message": f"Appium command timed out after {timeout}s",
                        "retryable": True,
                    }
                ],
                metrics={"stdout": str(exc.stdout or ""), "stderr": str(exc.stderr or "")},
            )
        parsed = self._parse_summary(completed.stdout)
        failed = int(parsed.get("failed") or (1 if completed.returncode else 0))
        passed = int(parsed.get("passed") or 0)
        skipped = int(parsed.get("skipped") or 0)
        status = "passed" if completed.returncode == 0 and failed == 0 else "failed"
        artifacts = self._collect_files(plan)
        failures = []
        if status == "failed":
            failures.append(
                {
                    "id": "appium-command",
                    "category": "runner_error",
                    "message": completed.stderr or completed.stdout or f"exit code {completed.returncode}",
                    "retryable": False,
                }
            )
        return ExecutionResult(
            run_id=plan.id,
            runner=self.name,
            status=status,
            summary={
                "passed": passed,
                "failed": failed,
                "skipped": skipped,
                "duration_ms": int((time.monotonic() - started) * 1000),
            },
            failures=failures,
            artifacts=artifacts,
            metrics={"returncode": completed.returncode, "command": argv, "stdout": completed.stdout},
        )

    @staticmethod
    def _parse_summary(stdout: str) -> dict[str, Any]:
        for line in reversed(stdout.splitlines()):
            try:
                payload = json.loads(line)
            except json.JSONDecodeError:
                continue
            if isinstance(payload, dict):
                return payload
        return {}

    @staticmethod
    def _collect_files(plan: ExecutionPlan) -> list[dict[str, Any]]:
        roots = [Path(str(item)) for item in plan.fixtures.get("artifact_paths") or []]
        artifacts: list[dict[str, Any]] = []
        for root in roots:
            candidates = [root] if root.is_file() else sorted(root.rglob("*")) if root.exists() else []
            for path in candidates:
                if path.is_file():
                    artifacts.append({"path": str(path), "kind": "mobile-artifact", "contract": None})
        return artifacts
